%% Optimization test with MATLAB algorithms
clear all

functions = {'Sphere function',...
    'Ellipsoid function',...
    'Rotated Ellipsoid function',...
    'Step function',...
    'Ackley''s function',...
    'Griewank''s function',...
    'Rosenbrock''s function',...
    'Rastrigin''s function'};
ranges = {[-5.12,5.12],...
    [-5.12,5.12],...
    [-5.12,5.12],...
    [-5.12,5.12],...
    [-32,32],...
    [-600,600],...
    [-2.048,2.048],...
    [-5.12,5.12]
    };

javaaddpath('bin')
eotp = cec14.eotp();

test_num = 100;

func_nos = randi([1 8],test_num,1);
dims = randi([1 3], test_num,1);
strs = {'Test','Function no.', 'Dimesnion', 'Problem no.', 'Java code', 'Matlab Code','Error'};
cellfun(@(x)(fprintf('%15s',x)),strs(1:4));
cellfun(@(x)(fprintf('%25s',x)),strs(5:7));
fprintf('\n');
for i=1:test_num
    r = ranges{func_nos(i)};
    x = rand(dims(i)*10,1) * range(r) + r(1);
    problem_no = (func_nos(i)-1)*3 + dims(i);
    ret = eotp.cec14_eotp_probems(x, problem_no);
    ret2 = cec14_eotp_problems(x,problem_no);
%     assert(ret==ret2,'Test %d : Function error for problem %d, dim = %d.',...
%         i, func_nos(i), dims(i)*10);    
    fprintf('%15d', [i, func_nos(i), dims(i)*10, problem_no]);
    fprintf('%25.12e', [ret ret2 abs(ret-ret2)]);
    fprintf('\n');
    %assert(abs(ret-ret2)<1e-10,'Significant error exist in c++ code : %.16f.',abs(ret-ret2));
end

